### ISSUE TITLE
add stargate link address to the read me

### ISSUE THREAD

**Issue by FemiOluwadamilola** [eddiejaoude/stargate#9] opened 2021-02-26 17:40 UTC
I think adding link to the landing page of stargate to the readme would be great

**Comment by Vyvy-vi** [comment] 2021-02-26 17:55
duplicate of #5

**Closed** 2021-02-26 17:59 UTC

**Comment by eddiejaoude** [comment] 2021-03-02 23:59
Thank you for raising the issue 👍 closed issues/prs still get 🟩
